refcodes:
  examplecode: "give %player% minecraft:diamond 5"

messages:
  ipAlreadyUsed: "Этот IP уже использовал реферальный код."
  codeUsed: "Вы использовали реферальный код!"
  referrerReward: "Игрок, которого вы пригласили, использовал ваш реферальный код!"
  invalidCode: "Реферальный код недействителен."
  invalidReferrer: "Реферальный код недействителен или вы не можете использовать свой собственный код."
  insufficientPlayTime: "Вы не можете использовать реферальный код до того, как наиграете 2 часа на сервере."
  usage: "Используйте: /ref <код>"

command:
  name: "ref"
  description: "Использовать реферальный код"
  usage: "/ref <код>"
  permission: "referralsystem.use"



  # LifeTime <3
